// All property listings. Rendered by listings.js on the homepage (featured)
// and listings.html (full catalogue).
window.LISTINGS = [
 { slug: "harper-street-surry-hills", img: "images/listing-1.jpg?v=1", name: "Harper Street", suburb: "Surry Hills", desc: "Stunning terrace home with original sandstone features and a private rear courtyard, moments from Crown Street's dining and boutiques.", beds: 3, baths: 2, cars: 1, rent: 1150, status: "leased" },
 { slug: "clifton-avenue-glebe", img: "images/listing-2.jpg?v=1", name: "Clifton Avenue", suburb: "Glebe", desc: "Architect-renovated Victorian villa with polished timber floors, a sky-lit kitchen and a lush rear garden.", beds: 3, baths: 2, cars: 1, rent: 1050, status: "rent" },
 { slug: "cascade-street-paddington", img: "images/listing-3.jpg?v=1", name: "Cascade Street", suburb: "Paddington", desc: "Classic Paddington terrace with decorative iron lacework, updated interiors and a sunny roof terrace.", beds: 2, baths: 1, cars: 0, rent: 980, status: "leased" },
 { slug: "darling-street-balmain", img: "images/listing-4.jpg?v=1", name: "Darling Street", suburb: "Balmain", desc: "Federation-era home on the village's main strip, fully updated with modern kitchen and stone-appointed bathrooms.", beds: 3, baths: 2, cars: 1, rent: 1200, status: "rent" },
 { slug: "norton-street-leichhardt", img: "images/listing-5.jpg?v=1", name: "Norton Street", suburb: "Leichhardt", desc: "Freshly renovated cottage steps from Norton Street piazza with an open plan living zone and sunny alfresco.", beds: 2, baths: 1, cars: 1, rent: 880, status: "rent" },
 { slug: "raglan-street-mosman", img: "images/listing-6.jpg?v=1", name: "Raglan Street", suburb: "Mosman", desc: "Spacious upper-level apartment with harbour glimpses, a double garage and a short walk to Mosman village.", beds: 3, baths: 2, cars: 2, rent: 1500, status: "leased" },
 { slug: "brown-street-newtown", img: "images/listing-7.jpg?v=1", name: "Brown Street", suburb: "Newtown", desc: "Renovated terrace on a quiet tree-lined block, moments from King Street cafes and Newtown station.", beds: 2, baths: 1, cars: 0, rent: 950, status: "rent" },
 { slug: "waterloo-street-teneriffe", img: "images/listing-8.jpg?v=1", name: "Waterloo Street", suburb: "Teneriffe", desc: "Premium apartment in a converted wool store with soaring ceilings, polished concrete and river views.", beds: 2, baths: 2, cars: 1, rent: 950, status: "rent" },
 { slug: "la-trobe-terrace-paddington-qld", img: "images/listing-9.jpg?v=1", name: "La Trobe Terrace", suburb: "Paddington", desc: "Timeless Queenslander on prestigious La Trobe Terrace with wraparound veranda and city views.", beds: 4, baths: 2, cars: 2, rent: 1050, status: "leased" },
 { slug: "james-street-new-farm", img: "images/listing-10.jpg?v=1", name: "James Street", suburb: "New Farm", desc: "Boutique luxury apartment moments from the James Street dining precinct and Teneriffe riverside.", beds: 2, baths: 2, cars: 1, rent: 900, status: "rent" },
 { slug: "boundary-street-west-end", img: "images/listing-11.jpg?v=1", name: "Boundary Street", suburb: "West End", desc: "Character cottage with north-facing deck, polished floors and a private garden steps from Boundary Street.", beds: 3, baths: 1, cars: 1, rent: 800, status: "rent" },
 { slug: "oxford-street-bulimba", img: "images/listing-12.jpg?v=1", name: "Oxford Street", suburb: "Bulimba", desc: "Contemporary townhouse in the Oxford Street village precinct with double garage and landscaped courtyard.", beds: 3, baths: 2, cars: 2, rent: 950, status: "leased" },
 { slug: "racecourse-road-ascot", img: "images/listing-13.jpg?v=1", name: "Racecourse Road", suburb: "Ascot", desc: "Elegant post-war home in the prestige Ascot corridor, featuring formal and informal living across two levels.", beds: 4, baths: 3, cars: 2, rent: 1100, status: "rent" },
 { slug: "riverview-terrace-hamilton", img: "images/listing-14.jpg?v=1", name: "Riverview Terrace", suburb: "Hamilton", desc: "Architect-designed home on the Hamilton hill with sweeping river views and a resort-style pool terrace.", beds: 4, baths: 3, cars: 2, rent: 1200, status: "leased" },
 { slug: "toorak-road-south-yarra", img: "images/listing-15.jpg?v=1", name: "Toorak Road", suburb: "South Yarra", desc: "Sun-drenched apartment with premium finishes, a gourmet kitchen and direct access to Chapel Street shopping.", beds: 2, baths: 2, cars: 1, rent: 1100, status: "rent" },
 { slug: "smith-street-collingwood", img: "images/listing-16.jpg?v=1", name: "Smith Street", suburb: "Collingwood", desc: "Industrial-chic loft in a converted warehouse with exposed brick, high ceilings and a private rooftop terrace.", beds: 2, baths: 1, cars: 1, rent: 950, status: "leased" },
 { slug: "fitzroy-street-st-kilda", img: "images/listing-17.jpg?v=1", name: "Fitzroy Street", suburb: "St Kilda", desc: "Art Deco character apartment steps from St Kilda Beach, freshly updated with designer touches throughout.", beds: 2, baths: 1, cars: 1, rent: 870, status: "rent" },
 { slug: "brunswick-street-fitzroy", img: "images/listing-18.jpg?v=1", name: "Brunswick Street", suburb: "Fitzroy", desc: "Beautifully restored Victorian terrace on sought-after Brunswick Street with a private courtyard and cellar.", beds: 3, baths: 2, cars: 0, rent: 1050, status: "rent" },
 { slug: "richmond-terrace-richmond", img: "images/listing-19.jpg?v=1", name: "Richmond Terrace", suburb: "Richmond", desc: "Stylish modern townhouse with rooftop entertaining, minutes from Bridge Road dining and the MCG.", beds: 3, baths: 2, cars: 1, rent: 1000, status: "leased" },
 { slug: "sydney-road-brunswick", img: "images/listing-20.jpg?v=1", name: "Sydney Road", suburb: "Brunswick", desc: "Terrace-style home blending original period detail with a contemporary rear extension and a productive vegetable garden.", beds: 3, baths: 2, cars: 1, rent: 900, status: "rent" },
];
